jobs:
  publish:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Repo
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - continue-on-error: true
      name: Build
      run: ./gradlew build
    - continue-on-error: true
      env:
        DEXMAKER_GPG_PRIVATE_KEY: ${{ secrets.DEXMAKER_GPG_PRIVATE_KEY }}
        DEXMAKER_GPG_PRIVATE_KEY_PASSWORD: ${{ secrets.DEXMAKER_GPG_PRIVATE_KEY_PASSWORD
          }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
      name: Publish package
      run: ./gradlew publishAllPublicationsToMavenCentralRepository
name: Publish package to the Maven Central Repository
on:
  repository_dispatch:
    types: trigger-ga___publish-maven-central.yml
